Settings:
  debug: false
  proxy: false
  save_to_path: /workspaces/Project-Skidhub
  save_to_path_automatic: true
  threads: 1
  timeout: 10
  user_agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2) Gecko/20100101 Firefox/10.0.2
  verbose: true
